---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: webhook
  labels:
    app: client-webhook
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
  selector:
    app: client-webhook
