---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: webhook
  labels:
    app: pinax-cloud
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: pinax-cloud
