---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinax-cloud
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinax-cloud
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pinax-cloud
    spec:
      containers:
        - name: pinax-cloud
          image: ghcr.io/gcleroux/pinax-cloud-webhooks/pinax-cloud-webhooks.deno:v0.1.0 # {"$imagepolicy": "flux-system:pinax-cloud"}
          env:
            - PORT: 30030
          ports:
            - containerPort: 30030
