---
apiVersion: v1
kind: Service
metadata:
  name: svc-pinax-cloud
  namespace: default
  labels:
    app: pinax-cloud
spec:
  type: ClusterIP
  ports:
    - port: 30030
      targetPort: 30030
      protocol: TCP
  selector:
    app: pinax-cloud
