---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flagger
  namespace: istio-system
spec:
  interval: 1h0m0s
  path: ./kustomize/istio
  prune: true
  sourceRef:
    kind: GitRepository
    name: flagger-repo
  timeout: 5m0s
  wait: true
