---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 1h0m0s
  path: ./monitoring/monitoring-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m0s
  wait: true
