---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  install:
    disableWait: false
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio-helm-repo
        namespace: istio-system
  interval: 5m
