apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-deployment-substreams
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo-substreams
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: repo-substreams
    spec:
      containers:
        - name: repo-substreams-prometheus-sink
          image: ghcr.io/gcleroux/substreams-sink-prometheus:v4.20.69 # {"$imagepolicy": "flux-system:repo-substreams"}
          args:
            [
              "run",
              "https://github.com/pinax-network/substreams/releases/download/eosmechanics-v0.3.6/eosmechanics-v0.3.6.spkg",
              "prom_out",
              "-e",
              "https://eos.firehose.eosnation.io:9001",
              "--verbose",
              "-s",
              "-1",
              "--address",
              "0.0.0.0"
            ]
          ports:
            - containerPort: 9102
