---
apiVersion: v1
kind: Service
metadata:
  name: svc-repo
  namespace: default
  labels:
    app: repo-substreams
spec:
  type: NodePort
  ports:
    - port: 9102
      nodePort: 30002
      targetPort: 9102
      protocol: TCP
  selector:
    app: repo-substreams
