---
apiVersion: v1
kind: Service
metadata:
  name: repo-substreams-exporter
  namespace: default
  labels:
    app: repo-substreams
spec:
  selector:
    app: repo-substreams
  type: ClusterIP
  ports:
    - name: metrics
      protocol: TCP
      port: 9102
      targetPort: 9102
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: repo-substreams-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: repo-substreams
  endpoints:
    - port: metrics
