commonLabels:
  network: eos

defaultRules:
  ## Labels for default rules
  labels:
    network: eos
  ## Annotations for default rules
  annotations:
    network: eos

  ## Additional labels for PrometheusRule alerts
  additionalRuleLabels:
    network: eos

  ## Additional annotations for PrometheusRule alerts
  additionalRuleAnnotations:
    network: eos

prometheus:
  prometheusSpec:
    externalLabels:
      network: eos
