# https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: private-test
  namespace: default
  labels:
    app: private-test
spec:
  containers:
    - name: private-test
      image: ghcr.io/gcleroux/test:main
  imagePullSecrets:
    - name: ghcr-login-secret
  restartPolicy: Never
