---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - flux-system-automation.yml
  - substreams-prometheus-policy.yml
  - substreams-prometheus-registry.yml
