---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: repo-substreams
  namespace: flux-system
spec:
  image: ghcr.io/gcleroux/substreams-sink-prometheus
  interval: 1m0s
