---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-test
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: private-test
    spec:
      containers:
        - name: private-test
          image: ghcr.io/gcleroux/test
