---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - flux-system-automation.yaml
  - substreams-webhook-policy.yaml
  - substreams-webhook-registry.yaml
