---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - flux-system-automation.yml
  - substreams-webhook-policy.yml
  - substreams-webhook-registry.yml
