---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: substreams-webhook
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: substreams-webhook
  policy:
    semver:
      range: "*"
